service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: backend-service-1-tyygvmxafm
  name: backend-service-1-tyygvmxafm
  selector: backend-service-1-tyygvmxafm
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-backend-service-1-tyygvmxafm
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-1-tyygvmxafm
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: backend-service-1-tyygvmxafm
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: backend-service-1-tyygvmxafm
    port: 8080
  volume:
    name: pvc-backend-service-1-tyygvmxafm
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-1-tyygvmxafm
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
