service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: backend-service-1-tyygvmxafm
  name: backend-service-1-tyygvmxafm
  selector: backend-service-1-tyygvmxafm
  type:
  - ClusterIP
  - NodePort
namespace: pr-test-dev
pvc:
  name: pvc-backend-service-1-tyygvmxafm
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-1-tyygvmxafm
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/stage-turaco-workspace-249/turaco
  image:
    name: backend-service-1-tyygvmxafm
    tag: "1615-1669-backend-service-1-tyygvmxafm-553ecfc"
    secret: regsecret
  container:
    name: backend-service-1-tyygvmxafm
    port: 8080
  volume:
    name: pvc-backend-service-1-tyygvmxafm
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-1-tyygvmxafm
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
